import './globals.css'
import '@/src/fonts/tln-fonts/style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MainLayout } from '@/src/components/layout/Mainlayout'
import Providers from '@/src/utils/provider'
import StyledComponentsRegistry from '@/src/lib/AntdRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StyledComponentsRegistry>
            <MainLayout>{children}</MainLayout>
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  )
}
